import csv
from ics import Calendar, Event
from datetime import datetime
import arrow
import argparse

def csv_to_ics(csv_in_path, ics_out_path):
    with open(csv_in_path) as csv_file:
        csv_reader = csv.DictReader(csv_file)

        cal = Calendar()
        for row in csv_reader:
            if row["Time"][0] != " ":
                row["Time"] = " " + row["Time"]
            date = datetime.strptime(row["Date"] + row["Time"], "%Y-%m-%d %I:%M%p")
            date = arrow.get(date, "US/Pacific")
            if "Sagres" in row["home_team"]:
                team = row["visit_team"]
                home_status = "Home"
            else:
                team = row["home_team"]
                home_status = "Away"
            team = row["home_team"] if "Sagres" in row["visit_team"] else row["visit_team"]
            e = Event()
            e.name = f"{team} ({home_status})"
            e.begin = date
            e.location = row["field_name"]
            print(f"{e.name} @ {e.location} @ {e.begin}\n")

            cal.events.add(e)

        with open(ics_out_path, 'w') as ics_file:
            ics_file.writelines(cal.serialize_iter())

def main():
    parser = argparse.ArgumentParser(description="Parses the csv generated by visl.org's schedule filter feature to generate an importable calendar file (ics file). "
        "CSV generated via the Excel button on the page.")
    parser.add_argument("-c", "--csv_in_file", required=True)
    parser.add_argument("-i", "--ics_out_file", required=True)

    args = parser.parse_args()
    csv_to_ics(args.csv_in_file, args.ics_out_file)

if __name__ == "__main__":
    main()
